name: 'krane-deploy-action'
description: |
  A github action to deploy services to kubernetes with https://github.com/Shopify/krane.
  this requires smartlyio/kubernetes-auth-action to be run first to configure acess to the cluster in use.
author: 'Smartly.io'
inputs:
  currentSha:
    description: 'Current source revision'
    required: true
  dockerRegistry:
    description: 'Docker registry URI'
    required: true
  kubernetesContext:
    description: 'Kubernetes context name. Usually the name of the cluster, but can be random'
    required: true
  kubernetesClusterDomain:
    description: 'Fully qualified domain name of the cluster.'
    required: true
  kubernetesNamespace:
    description: 'Kubernetes namespace name. Should be similar to service name'
    required: true
  kubernetesTemplateDir:
    description: 'Directory with production manifests'
    required: false
    default: './kubernetes/production'
  kraneSelector:
    description: 'Label selector for krane-managed kubernetes assets'
    required: false
    default: 'smartly.io/managed-by=krane'
  kranePath:
    description: 'Alternative path to krane binary (default krane on PATH)'
    required: false
    default: 'krane'
  extraBindings:
    description: 'Additional template variable bindings to use in the krane render step; formatted as a JSON object mapping binding name to value.'
    required: false
    default: '{}'
  renderOnly:
    description: 'Only render templates, do not deploy. Default false (i.e. render and deploy) [true/false].'
    required: false
    default: 'false'
  deployTimeout:
    description: 'Global timeout for krane deploy. Override this if a deployment is expected to take more than 10 minutes.'
    required: false
    default: '600s'
runs:
  using: 'node12'
  main: 'dist/index.js'
