name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run pack

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build action for test"
      run: |
        npm run all
    - run: |
        # Mock the krane executable
        echo '#!/usr/bin/env bash' > ./krane.sh
        echo 'echo "$@"' >> ./krane.sh
        chmod u+x ./krane.sh
        # Make a dummy template directory
        mkdir ./templates
        echo 'kind: Service' > ./templates/manifest.yml
        echo 'kind: Deployment' > ./templates/template.yml.erb
        touch ./templates/secrets.ejson
    - name: Test rendering only
      uses: ./
      env:
        KRANE_BINDING_binding2: value2
      with:
        currentSha: ${{ github.sha }}
        dockerRegistry: testRegistry
        kubernetesClusterDomain: cluster.example.com
        kubernetesContext: testContext
        kubernetesNamespace: testNamespace
        kubernetesTemplateDir: ./templates
        kranePath: ./krane.sh
        renderOnly: true
        extraBindings: |
          {
            "deployer": "user"
          }
    - name: Test render and deploy
      uses: ./
      env:
        KRANE_BINDING_binding2: value2
      with:
        currentSha: ${{ github.sha }}
        dockerRegistry: testRegistry
        kubernetesClusterDomain: cluster.example.com
        kubernetesContext: testContext
        kubernetesNamespace: testNamespace
        kubernetesTemplateDir: ./templates
        kranePath: ./krane.sh
        deployTimeout: 30s
        extraBindings: |
          {
            "deployer": "user"
          }
